name: "e2e"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "NOTICE"
      - "LICENSE"
  push:
    paths-ignore:
      - "**/*.md"
      - "NOTICE"
      - "LICENSE"
    branches:
      - "main"

env:
  # Github runner's extra disk is mounted on the /mnt directory.
  MINIKUBE_HOME: "/mnt/"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        label-filter:
          - full-backup
          - incremental-backup
          - misc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Free up disk space
        run: |
          df -h /
          sudo rm -rf /usr/share/dotnet /usr/local/.ghcup /usr/local/lib/android
          df -h /

      - name: Make /mnt accessible from `runner` user
        run: |
          sudo chown runner:runner /mnt

      - uses: ./.github/actions/set-up-kvm-for-e2e-tests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: controller:latest
          load: true
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}

      - name: Setup minikube with kvm2 driver
        run: |
            make -C test/e2e launch-minikube

      - name: Load image into minikube
        run: |
            make -C test/e2e image-tar-load
            # Display disk usage after loading image
            df -h /

      - name: Launch rook-ceph and deploy components
        run: |
          make -C test/e2e launch-rook-ceph
          make -C test/e2e setup-fin-volume
          make -C test/e2e setup-components

      - name: Run e2e tests
        run: |
          make -C test/e2e do-test \
          GINKGO_FLAGS=--label-filter='${{ matrix.label-filter }}'
